[font]
name = "testing font" # Name of your font (if you want)
path = "/usr/share/fonts/TTF/SpaceMonoNerdFont-Regular.ttf" # Path of chosen font 

[bg]
name = "Pink Floyd" # Name of your background (if you want)
path = "/home/nots1dd/wallpapers/wal19.png" # Path of chosen font

[debug]
debug_log_enable = "false" # Will display a LOT of pointer, keyboard, shader, etc. interfaces' debug logs

[time]
time_format = "H:M:S" # Can currently set to H:M or H:M:S 
