name: "Building Anvilock in Ubuntu (x86-64 arch - GCC/Clang)"

on:
  push:
    branches: [ "main" ]  # Trigger on push to the 'main' branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the 'main' branch

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies for Anvilock
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwayland-dev libxkbcommon-dev libpam0g-dev \
          libgles2-mesa-dev libfreetype6-dev cmake make \
          clang wget pkg-config wayland-protocols

    - name: Build Release Version of Anvilock (x86-64 arch) - GCC
      run: |
        make release

    - name: Build Release Version of Anvilock (x86-64 arch) - Clang
       run: |
         make clean
         make release FLAGS="-DUSE_CLANG=ON"
