name: Release Build for Anvilock

on:
  push:
    branches: [ "main" ]  # Trigger on push to 'main' (but only release if version changes)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl \

      - name: Get current version from repo
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Get latest release version
        id: get_latest_release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          if [[ "$LATEST_VERSION" == "null" ]]; then
            LATEST_VERSION="0.0.0"  # Default if no previous release exists
          fi
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Compare versions
        id: check_version
        run: |
          if [[ "${{ env.VERSION }}" == "${{ env.LATEST_VERSION }}" ]]; then
            echo "No version change detected. Skipping release."
            exit 1
          fi
          echo "New version detected: ${{ env.VERSION }}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gcc clang libwayland-dev \
            libxkbcommon-dev libpam0g-dev libegl1-mesa-dev libgles2-mesa-dev \
            libfreetype6-dev

      - name: Build Release Version of Anvilock
        run: |
          make release

      - name: Create Tarball
        run: |
          cd build
          tar -czvf ../anvilock.tar.gz anvilock
          cd ..

      - name: Upload Release for Anvilock
        uses: softprops/action-gh-release@v2
        with:
          files: |
            anvilock.tar.gz
          tag_name: ${{ env.VERSION }}
          name: "Anvilock ${{ env.VERSION }} - Release"
          body: |
            **Anvilock ${{ env.VERSION }} - Release Notes**
            
            ### How to Install:
            ```
            tar -xvzf anvilock.tar.gz
            ./anvilock
            ```

            _Thanks for using Anvilock!_

